config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  resources :users do
    member do
      get :following, :followers, :liked_posts, :all_users
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts do
    resource :likes, only: [:create, :destroy]
    member do
      get :liked_users # micropost id の配下でユーザーを表示できる。
    end
  end
  resources :follows
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  has_many :likes, dependent: :destroy
  has_many :likeusers, through: :likes, source: :user
  
  def liked?(user)
    likes.where(user_id: user.id).exists?
  end
  
  def likedtime(user)
    likes.where(user_id: user.id).last.updated_at
  end
  # def liked_users(post)
  #   User.includes(:likes).where(likes: {micropost_id: post.id})
  # end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc) # この行を追加
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  def liked_users
    @title = "liked users list is below"
    @micropost = current_user.microposts.build
    @objmicropost = Micropost.find(params[:id])
    @users = @objmicropost.likeusers
    render 'show_likeduser'
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper

end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
     <% if current_user == micropost.user %>
          <%= link_to "delete", micropost_path(micropost), method: :delete, data: { confirm: "You sure?" } %>
     <% end %>
    <br/> 
    <%= link_to "#{micropost.likes.count} users like this posts", liked_users_micropost_path(micropost) %>

    <%- if false -%> <%# above code is same as below, but above has much more options%>
    <a href="<%= liked_users_micropost_path(micropost) %>"> 
        <strong id="liked_posts" class="stat"> 
          <%= micropost.likes.count%>
        </strong> 
            users like this posts 
    </a> 
    <%- end -%>
    
    <br/>
    <%= render partial: 'users/like', locals: { microposts: micropost } %>
  </span>
</li>

app/views/microposts/show_likeduser.html.erb
<div class="row">
  <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
  </aside>
  
  <div class="col-md-8">
    
      <%# Objective post %>
      <h3>Objective post</h3>
      <ol class="microposts">
      <%= render partial: 'micropost', locals: { micropost: @objmicropost } %>
      </ol>

      <%# Liked user list %>
      <h3><%= @title %></h3>
      <% if @users.any? %>
        <ol class="follows">
          <% @users.each do |follow| %>
            <%= render partial: 'follows/follow', locals: { follow: follow } %>
          <% end %>
        </ol>
      <% end %>

  </div>