config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  resources :users do
    member do
      get :following, :followers, :liked_posts, :all_users
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts do
    resource :likes, only: [:create, :destroy]
    member do
      get :liked_users # micropost id の配下でユーザーを表示できる。
    end
  end
  resources :follows
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  
   <%= link_to "Microposts", root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home(H)", root_path, accesskey:"H" %></li>
        <li><%= link_to "Help",   '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users(U)", users_path, accesskey:"U" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile(P)", current_user, accesskey:"P" %></li>
              <li><%= link_to "Settings(S)", edit_user_path(current_user), accesskey:"S" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in(I)", login_path, accesskey:"I" %></li>
        <% end %>
      </ul>
    </nav>
  
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microposts</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>